trigger:
- main

parameters:
- name: seedData
  type: boolean
  default: false
  displayName: Seed data to CosmosDB

variables:
  tag: '$(Build.BuildNumber)'
  containerRegistry: 'mbbacr'

stages:

- stage: Build
  displayName: Build and push stage

  variables:
    buildContextPath: '$(Build.SourcesDirectory)'

  jobs:
  - job: web_build
    displayName: Build Web

    pool:
      vmImage: 'ubuntu-latest'

    variables:
      imageRepository: 'whatisthecurrentsprint/web'
      dockerfilePath: '$(buildContextPath)/src/Web/Dockerfile'

    steps:
    - task: Docker@2
      displayName: Login to ACR
      inputs:
        command: login
        containerRegistry: |
          $(containerRegistry)

    - task: Docker@2
      displayName: Build image
      inputs:
        repository: $(imageRepository)
        command: build
        Dockerfile: $(dockerfilePath)
        buildContext: $(buildContextPath)
        tags: |
          $(tag)

    - task: Docker@2
      displayName: Push image
      inputs:
        containerRegistry: |
          $(containerRegistry)
        repository: $(imageRepository)
        command: push
        tags: |
          $(tag)

- stage: Deploy
  displayName: Deploy

  jobs:
  - job: web_deploy
    displayName: Deploy Web

    pool:
      vmImage: 'ubuntu-latest'

    variables:
      imageRepository: 'whatisthecurrentsprint/web'
      appName: 'witcs-app'

    steps:
      ## Add the below snippet at the end of your pipeline
    - task: AzureWebAppContainer@1
      displayName: Azure Web App on Container Deploy
      inputs:
        azureSubscription: 'Sandbox (63a92080-67fa-42c3-8276-13598194bce2)'
        appName: $(appName)
        imageName: $(containerRegistry).azurecr.io/$(imageRepository):$(tag)

  - job: seed_data
    displayName: Seed Data
    condition: eq('${{ parameters.seedData }}', true)

    pool:
      vmImage: 'ubuntu-latest'

    variables:
    - group: whatisthecurrentsprint

    steps:
      ## Add the below snippet at the end of your pipeline
    - task: PythonScript@0
      displayName: Run python script
      inputs:
        scriptSource: filePath
        scriptPath: ./.azure/scripts/seed-data/seeddata.py
        workingDirectory: ./.azure/scripts/seed-data
